### ISSUE TITLE
Axis don't show up with WUP-028

### ISSUE THREAD

**Issue by Hay1tsme** [bwiklund/gamepad.js#12]
Currently using a WUP-028 official Nintendo Gamecube adapter using the GCN USB Adapter software (WinUSB (v6.1.7600.16385) drivers) and the sticks (as well as the R and L button analogue inputs) do not show up on the viewer

**Comment by bwiklund** [comment]
the library iterates over whatever inputs the browser api reports, so if it's not showing up that's probably the reason
