### ISSUE TITLE
Controller polling rate / frequency

### ISSUE THREAD

**Issue by Dysp1** [bwiklund/gamepad.js#15]
There is no tool to check the rate at which the controllers send their inputs, like this one is for mouse:

https://zowie.benq.com/ja/support/mouse-rate-checker.html

For example there are tools to change DS4 wired usb polling rate from 250hz to 1000hz, but absolutely no tools to confirm if the controller actually is producing data at 1ms interval instead of 4ms.

I'm talking about the https://html5gamepad.com/ demo or test page. It's a great tool, that would be very usefull to check the polling rates also!

**Comment by bwiklund** [comment]
that's a cool idea, i'll add it next time im working on the site

**Comment by luser** [comment]
I'm not sure you could accurately get this information out of the Gamepad API in a browser, unfortunately. There are quite a few layers between the driver and the JavaScript code calling the Gamepad API, and different browsers have different internal architectures that can have a big impact. The Gamepad API itself also requires polling which is unfortunate. I prototyped some event-based APIs in Firefox but didn't do the work to spec them so they could be implemented in an interoperable fashion. (Writing specs is hard!)

**Comment by bwiklund** [comment]
yeah unfortunately this doesn't seem possible, i'll revisit it in the future
