### ISSUE TITLE
[Website] Add search, sort, filtering for controllers/codes

### ISSUE THREAD

**Issue by jsejcksn** [bwiklund/gamepad.js#17]
Since the pagination is for presentation only, and [the entire dataset](https://html5gamepad.com/logs/controllers) is downloaded to the client on page load, it would be nice to be able to search, sort, and filter the data.

Basic lowercase text `str.includes()` filtering would be a great start, but [fuzzy search](https://github.com/krisk/Fuse) would be even better.

Adding support for sorting by field would be great, too (reversing, sort by count/variant/etc.).

I'm sure you could get community help with this, but [I'm not sure how the website relates to this repo](https://github.com/bwiklund/gamepad.js/issues/16), since the site links to this repo, but there's not mention of a repo dedicated to the website source. Is there a repo for that purpose, or plans for one?

**Comment by nobodywasishere** [comment]
This repo is what the website used to look like. They haven't updated this source code even though they've updated the website, and since this isn't under an open source license, they have no obligation to release the code. Unfortunate, but it is what it is.

**Comment by bwiklund** [comment]
Hi there, thanks for taking the time to submit this issue. The site has moved on from the open source version, but all the relevant code for tracking gamepads is essentially the same. It's left here because people seemed interested in it.
