### ISSUE TITLE
>4 Gamepads

### ISSUE THREAD

**Issue by MattTreichelYeah** [bwiklund/gamepad.js#4]
This only shows 4 gamepads but theoretically could have more, right?

**Comment by bwiklund** [comment]
the use case seems vanishingly small but the perfectionist in me wants to make it work...

**Comment by bwiklund** [comment]
ill make it happen next time i revist this project

**Comment by MattTreichelYeah** [comment]
I actually did some more research into this, and it seems it's a complicated issue. Only FireFox supports more than 4 even though the spec doesn't imply a limit.

http://stackoverflow.com/questions/41251051/is-the-html5-gamepad-api-limited-to-only-4-controllers

**Comment by bwiklund** [comment]
oh, hm, actually:

https://github.com/bwiklund/gamepad.js/blob/master/source/javascripts/all.js.coffee#L7

https://github.com/bwiklund/gamepad.js/blob/master/source/index.html.slim#L16

i'm currently reporting whatever the browser reports, which in my case (chrome, windows) is a 4 element list with `null` elements if there's no gamepad there. so if/when browsers start being capable of reporting more, this project will report them as well

**Comment by MattTreichelYeah** [comment]
Yeah, that's what I mean, only FireFox actually allows more. Anyway, no problem, I made this issue more about asking the question before realizing I should check the browser/spec myself.
